FROM mcr.microsoft.com/dotnet/sdk:10.0

# Install additional tools
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    git \
    curl \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Install EF Core tools globally
RUN dotnet tool install --global dotnet-ef

# Add .NET tools to PATH
ENV PATH="${PATH}:/root/.dotnet/tools"
